version: '3.8'
services:

  mongoDb:
    image: mongo:5
    container_name: mongo_tank_monitor
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGODB_DATABASE: tank-monitor-db
    volumes:
      - /mongo:/data/db
    networks:
      - tank-monitor-network
  # devcontainer:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ../..:/workspaces:cached      
  #   ports:
  #     - ${PORT}:5555
  #   restart: always
  #   env_file: ".env"
  #   depends_on:
  #     - mongoDb
  #   container_name: tank_monitor_devcontainer
  #   networks:
  #     - tank-monitor-network

  

networks:
  tank-monitor-network:
    driver: bridge