version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached      
    ports:
      - ${PORT}:5555
    restart: always
    env_file: ".env"
    depends_on:
      - db
      - mongoDb
    container_name: lambda_devcontainer
    networks:
      - lambda-network

  

networks:
  lambda-network:
    driver: bridge